version: '3'

services:
  noticiasabelhudas:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes: 
      - .:/dotnet-app
      - ./NoticiasAbelhudasSQLite.db:/NoticiasAbelhudasSQLite.db
    working_dir: /dotnet-app
    command: dotnet run
    restart: unless-stopped
